package SumApp;


/**
* SumApp/SumServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sum.idl
* Wednesday, November 19, 2014 9:04:30 AM PST
*/

public interface SumServer extends SumServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SumServer
