package SumApp;

/**
* SumApp/SumServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sum.idl
* Wednesday, November 19, 2014 9:04:30 AM PST
*/

public final class SumServerHolder implements org.omg.CORBA.portable.Streamable
{
  public SumApp.SumServer value = null;

  public SumServerHolder ()
  {
  }

  public SumServerHolder (SumApp.SumServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SumApp.SumServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SumApp.SumServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SumApp.SumServerHelper.type ();
  }

}
