package SumApp;


/**
* SumApp/SumServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sum.idl
* Wednesday, November 19, 2014 9:04:30 AM PST
*/

abstract public class SumServerHelper
{
  private static String  _id = "IDL:SumApp/SumServer:1.0";

  public static void insert (org.omg.CORBA.Any a, SumApp.SumServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SumApp.SumServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SumApp.SumServerHelper.id (), "SumServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SumApp.SumServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SumServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SumApp.SumServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SumApp.SumServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SumApp.SumServer)
      return (SumApp.SumServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SumApp._SumServerStub stub = new SumApp._SumServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SumApp.SumServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SumApp.SumServer)
      return (SumApp.SumServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SumApp._SumServerStub stub = new SumApp._SumServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
