package SumApp;


/**
* SumApp/SumServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sum.idl
* Wednesday, November 19, 2014 9:04:30 AM PST
*/

public interface SumServerOperations 
{
  int sum (int a, int b);
} // interface SumServerOperations
