CC = g++-4.8

STUFF = question2 question3

all: question2 question3

question2:
	cd Question_2; make
	cd Question_2; cp question2 cd ..; rm question2

question3:
	cd Question_3; make
	cd Question_3; cp question3 cd ..; rm question3

clean:
	rm question2 rm question3

